name: Argo CD Create and Sync Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-sync-argo-app:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.2.4/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
          
      - name: Create Argo CD Application
        run: |
          argocd app create myapp-argo-application \
            --repo https://github.com/bbz1024/argocd-lab.git \
            --path dev \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace myapp \
            --sync-policy automated \
            --sync-option CreateNamespace=true \
            --self-heal \
            --prune

      - name: Sync Argo CD Application
        run: |
          argocd app sync myapp-argo-application --namespace myapp
